#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const root = path.join(__dirname, '..');
const envFile = path.join(root, '.env');
const profilesFile = path.join(root, 'config', 'mailboxes.json');
const exampleProfilesFile = path.join(root, 'config', 'mailboxes.example.json');

function ask(rl, question) {
  return new Promise(resolve => rl.question(question, answer => resolve(answer.trim())));
}

function askHidden(question) {
  return new Promise(resolve => {
    const stdin = process.stdin;
    const stdout = process.stdout;
    stdout.write(question);
    stdin.setRawMode?.(true);
    stdin.resume();
    stdin.setEncoding('utf8');
    let value = '';
    function onData(ch) {
      if (ch === '\u0003') process.exit(130);
      if (ch === '\r' || ch === '\n') {
        stdin.setRawMode?.(false);
        stdin.pause();
        stdin.removeListener('data', onData);
        stdout.write('\n');
        resolve(value);
        return;
      }
      if (ch === '\b' || ch === '\u007f') {
        value = value.slice(0, -1);
        return;
      }
      value += ch;
      stdout.write('*');
    }
    stdin.on('data', onData);
  });
}

function readProfiles() {
  const file = fs.existsSync(profilesFile) ? profilesFile : exampleProfilesFile;
  if (!fs.existsSync(file)) return [];
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (error) {
    console.error(`Cannot parse ${file}: ${error.message}`);
    return [];
  }
}

function writeEnv(values) {
  const lines = [
    '# Generated by npm run setup. Never commit this file.',
    `IMAP_USER=${values.IMAP_USER || ''}`,
    `IMAP_PASSWORD=${values.IMAP_PASSWORD || ''}`,
    `IMAP_HOST=${values.IMAP_HOST || 'imap.qq.com'}`,
    `IMAP_PORT=${values.IMAP_PORT || '993'}`,
    `IMAP_TLS=${values.IMAP_TLS || 'true'}`,
    `IMAP_REJECT_UNAUTHORIZED=${values.IMAP_REJECT_UNAUTHORIZED || 'false'}`,
    `MAILBOX=${values.MAILBOX || 'INBOX'}`,
    `MAIL_WEB_USER=${values.MAIL_WEB_USER || (values.IMAP_USER || '').split('@')[0] || ''}`,
    '',
  ];
  fs.writeFileSync(envFile, lines.join('\n'), 'utf8');
}

async function main() {
  console.log('Email invoice mailbox setup');
  console.log('Credentials are written only to local .env, which is git-ignored.');
  console.log('Use an app password / authorization code, not your normal mailbox password.\n');

  const profiles = readProfiles();
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  let selected = null;
  if (profiles.length) {
    console.log('Available mailbox profiles:');
    profiles.forEach((p, i) => console.log(`  ${i + 1}. ${p.name || p.IMAP_USER} (${p.IMAP_USER || 'no user'})`));
    console.log(`  ${profiles.length + 1}. Manual input`);
    const raw = await ask(rl, `Choose mailbox [1-${profiles.length + 1}]: `);
    const idx = Number(raw);
    if (idx >= 1 && idx <= profiles.length) selected = { ...profiles[idx - 1] };
  }

  if (!selected) {
    selected = {};
    selected.IMAP_USER = await ask(rl, 'IMAP_USER: ');
    selected.IMAP_HOST = await ask(rl, 'IMAP_HOST [imap.qq.com]: ') || 'imap.qq.com';
    selected.IMAP_PORT = await ask(rl, 'IMAP_PORT [993]: ') || '993';
    selected.IMAP_TLS = await ask(rl, 'IMAP_TLS [true]: ') || 'true';
    selected.MAILBOX = await ask(rl, 'MAILBOX [INBOX]: ') || 'INBOX';
    selected.MAIL_WEB_USER = await ask(rl, 'MAIL_WEB_USER optional: ');
  }

  rl.close();
  selected.IMAP_PASSWORD = await askHidden('IMAP_PASSWORD / app password: ');
  writeEnv(selected);
  console.log(`Saved local mailbox config to ${envFile}`);
  console.log('Next: npm run doctor');
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
